package com.guzhi.pay.channel.unicom.cxf.verifycodemanage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-02-24T10:52:09.450+08:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://ws.ifdp.womusic.cn/", name = "VerifyCodeManage")
@XmlSeeAlso({ ObjectFactory.class })
public interface VerifyCodeManage {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "codeLogin", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.verifycodemanage.CodeLogin")
    @WebMethod
    @ResponseWrapper(localName = "codeLoginResponse", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.verifycodemanage.CodeLoginResponse")
    public com.guzhi.pay.channel.unicom.cxf.verifycodemanage.Response codeLogin(
            @WebParam(name = "event", targetNamespace = "") com.guzhi.pay.channel.unicom.cxf.verifycodemanage.CodeLoginEvt event,
            @WebParam(name = "inextraInfo", targetNamespace = "") com.guzhi.pay.channel.unicom.cxf.InextraInfo inextraInfo)
            throws ResponseException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendLoginCode", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.verifycodemanage.SendLoginCode")
    @WebMethod
    @ResponseWrapper(localName = "sendLoginCodeResponse", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.verifycodemanage.SendLoginCodeResponse")
    public com.guzhi.pay.channel.unicom.cxf.verifycodemanage.Response sendLoginCode(
            @WebParam(name = "event", targetNamespace = "") com.guzhi.pay.channel.unicom.cxf.verifycodemanage.SendLoginCodeEvt event,
            @WebParam(name = "inextraInfo", targetNamespace = "") com.guzhi.pay.channel.unicom.cxf.InextraInfo inextraInfo)
            throws ResponseException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendVerifyCode", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.verifycodemanage.SendVerifyCode")
    @WebMethod
    @ResponseWrapper(localName = "sendVerifyCodeResponse", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.verifycodemanage.SendVerifyCodeResponse")
    public com.guzhi.pay.channel.unicom.cxf.verifycodemanage.Response sendVerifyCode(
            @WebParam(name = "arg0", targetNamespace = "") com.guzhi.pay.channel.unicom.cxf.verifycodemanage.SendVerifyCodeEvt arg0,
            @WebParam(name = "arg1", targetNamespace = "") com.guzhi.pay.channel.unicom.cxf.InextraInfo arg1)
            throws ResponseException_Exception;
}
