/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.guzhi.pay.thrift.gbpay;

import java.util.BitSet;
import java.util.Collections;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;

import org.apache.thrift.TBase;
import org.apache.thrift.TBaseHelper;
import org.apache.thrift.TException;
import org.apache.thrift.TFieldIdEnum;
import org.apache.thrift.TFieldRequirementType;
import org.apache.thrift.meta_data.FieldMetaData;
import org.apache.thrift.meta_data.FieldValueMetaData;
import org.apache.thrift.protocol.TField;
import org.apache.thrift.protocol.TProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.protocol.TProtocolUtil;
import org.apache.thrift.protocol.TStruct;
import org.apache.thrift.protocol.TType;

/**
 * 扣除虚拟货币
 * 2013/2/28新增
 */
public class PayMoneyRequest2 implements TBase<PayMoneyRequest2, PayMoneyRequest2._Fields>, java.io.Serializable,
        Cloneable {
    private static final TStruct STRUCT_DESC = new TStruct("PayMoneyRequest2");

    private static final TField gbUID_FIELD_DESC = new TField("gbuid", TType.I64, (short) 1);
    private static final TField ORDER_ID_FIELD_DESC = new TField("orderId", TType.STRING, (short) 2);
    private static final TField MONEY_TYPE_FIELD_DESC = new TField("moneyType", TType.I32, (short) 3);
    private static final TField MONEY_FIELD_DESC = new TField("money", TType.STRING, (short) 4);
    private static final TField PRODUCT_FIELD_DESC = new TField("product", TType.STRING, (short) 5);
    private static final TField PAY_TIME_FIELD_DESC = new TField("payTime", TType.STRING, (short) 6);
    private static final TField USER_IP_FIELD_DESC = new TField("userIp", TType.STRING, (short) 7);
    private static final TField GOODS_NAME_FIELD_DESC = new TField("goodsName", TType.STRING, (short) 8);
    private static final TField DESCRIPTION_FIELD_DESC = new TField("description", TType.STRING, (short) 9);
    private static final TField CALLBACK_ADDR_FIELD_DESC = new TField("callbackAddr", TType.STRING, (short) 10);
    private static final TField SIGN_FIELD_DESC = new TField("sign", TType.STRING, (short) 11);
    private static final TField gb_CHANNEL_ID_FIELD_DESC = new TField("gbChannelId", TType.I64, (short) 12);
    private static final TField CONSUME_TARGET_PRODUCT_FIELD_DESC = new TField("consumeTargetProduct", TType.STRING,
            (short) 13);
    private static final TField ADD_MONEY_ORDER_ID_FIELD_DESC = new TField("addMoneyOrderId", TType.STRING, (short) 14);

    /**
     * gbuid
     */
    public long gbuid;
    /**
     * 业务方订单号
     */
    public String orderId;
    /**
     * 货币类型
     */
    public int moneyType;
    /**
     * 扣除的多玩币，单位：元，最小单位：0.01元
     */
    public String money;
    /**
     * 应用ID，比如gb音乐叫gbMUSIC
     */
    public String product;
    /**
     * 扣除多玩币的时间
     */
    public String payTime;
    /**
     * 用户客户端IP
     */
    public String userIp;
    /**
     * 商品名称，最长50字符
     */
    public String goodsName;
    /**
     * 描述，最长100个字符
     */
    public String description;
    /**
     * 回调地址(格式"host:port")或http://
     */
    public String callbackAddr;
    /**
     * md5校验码
     */
    public String sign;
    /**
     * gb频道ID，兼容旧接口的参数，可以填0
     */
    public long gbChannelId;
    /**
     * 消费到哪个产品里，最长20字符，一般等于""，像开放平台、充值中心这种业务，consumeTargetProduct=游戏/应用ID，
     */
    public String consumeTargetProduct;
    /**
     * addMoney()时的产品订单ID，当提供此ID，并且这个ID实际存在时，不会返回弹窗确认授权
     */
    public String addMoneyOrderId;

    /**
     * The set of fields this struct contains, along with convenience methods
     * for finding and manipulating them.
     */
    public enum _Fields implements TFieldIdEnum {
        /**
         * gbuid
         */
        gbUID((short) 1, "gbuid"),
        /**
         * 业务方订单号
         */
        ORDER_ID((short) 2, "orderId"),
        /**
         * 货币类型
         */
        MONEY_TYPE((short) 3, "moneyType"),
        /**
         * 扣除的多玩币，单位：元，最小单位：0.01元
         */
        MONEY((short) 4, "money"),
        /**
         * 应用ID，比如gb音乐叫gbMUSIC
         */
        PRODUCT((short) 5, "product"),
        /**
         * 扣除多玩币的时间
         */
        PAY_TIME((short) 6, "payTime"),
        /**
         * 用户客户端IP
         */
        USER_IP((short) 7, "userIp"),
        /**
         * 商品名称，最长50字符
         */
        GOODS_NAME((short) 8, "goodsName"),
        /**
         * 描述，最长100个字符
         */
        DESCRIPTION((short) 9, "description"),
        /**
         * 回调地址(格式"host:port")或http://
         */
        CALLBACK_ADDR((short) 10, "callbackAddr"),
        /**
         * md5校验码
         */
        SIGN((short) 11, "sign"),
        /**
         * gb频道ID，兼容旧接口的参数，可以填0
         */
        gb_CHANNEL_ID((short) 12, "gbChannelId"),
        /**
         * 消费到哪个产品里，最长20字符，一般等于""，像开放平台、充值中心这种业务，consumeTargetProduct=游戏/应用ID，
         */
        CONSUME_TARGET_PRODUCT((short) 13, "consumeTargetProduct"),
        /**
         * addMoney()时的产品订单ID，当提供此ID，并且这个ID实际存在时，不会返回弹窗确认授权
         */
        ADD_MONEY_ORDER_ID((short) 14, "addMoneyOrderId");

        private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

        static {
            for (_Fields field : EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not
         * found.
         */
        public static _Fields findByThriftId(int fieldId) {
            switch (fieldId) {
            case 1: // gbUID
                return gbUID;
            case 2: // ORDER_ID
                return ORDER_ID;
            case 3: // MONEY_TYPE
                return MONEY_TYPE;
            case 4: // MONEY
                return MONEY;
            case 5: // PRODUCT
                return PRODUCT;
            case 6: // PAY_TIME
                return PAY_TIME;
            case 7: // USER_IP
                return USER_IP;
            case 8: // GOODS_NAME
                return GOODS_NAME;
            case 9: // DESCRIPTION
                return DESCRIPTION;
            case 10: // CALLBACK_ADDR
                return CALLBACK_ADDR;
            case 11: // SIGN
                return SIGN;
            case 12: // gb_CHANNEL_ID
                return gb_CHANNEL_ID;
            case 13: // CONSUME_TARGET_PRODUCT
                return CONSUME_TARGET_PRODUCT;
            case 14: // ADD_MONEY_ORDER_ID
                return ADD_MONEY_ORDER_ID;
            default:
                return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null)
                throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not
         * found.
         */
        public static _Fields findByName(String name) {
            return byName.get(name);
        }

        private final short _thriftId;
        private final String _fieldName;

        _Fields(short thriftId, String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        public short getThriftFieldId() {
            return _thriftId;
        }

        public String getFieldName() {
            return _fieldName;
        }
    }

    // isset id assignments
    private static final int __gbUID_ISSET_ID = 0;
    private static final int __MONEYTYPE_ISSET_ID = 1;
    private static final int __gbCHANNELID_ISSET_ID = 2;
    private BitSet __isset_bit_vector = new BitSet(3);

    public static final Map<_Fields, FieldMetaData> metaDataMap;
    static {
        Map<_Fields, FieldMetaData> tmpMap = new EnumMap<_Fields, FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.gbUID, new FieldMetaData("gbuid", TFieldRequirementType.REQUIRED, new FieldValueMetaData(
                TType.I64)));
        tmpMap.put(_Fields.ORDER_ID, new FieldMetaData("orderId", TFieldRequirementType.REQUIRED,
                new FieldValueMetaData(TType.STRING)));
        tmpMap.put(_Fields.MONEY_TYPE, new FieldMetaData("moneyType", TFieldRequirementType.REQUIRED,
                new FieldValueMetaData(TType.I32)));
        tmpMap.put(_Fields.MONEY, new FieldMetaData("money", TFieldRequirementType.REQUIRED, new FieldValueMetaData(
                TType.STRING)));
        tmpMap.put(_Fields.PRODUCT, new FieldMetaData("product", TFieldRequirementType.REQUIRED,
                new FieldValueMetaData(TType.STRING)));
        tmpMap.put(_Fields.PAY_TIME, new FieldMetaData("payTime", TFieldRequirementType.REQUIRED,
                new FieldValueMetaData(TType.STRING)));
        tmpMap.put(_Fields.USER_IP, new FieldMetaData("userIp", TFieldRequirementType.REQUIRED, new FieldValueMetaData(
                TType.STRING)));
        tmpMap.put(_Fields.GOODS_NAME, new FieldMetaData("goodsName", TFieldRequirementType.REQUIRED,
                new FieldValueMetaData(TType.STRING)));
        tmpMap.put(_Fields.DESCRIPTION, new FieldMetaData("description", TFieldRequirementType.REQUIRED,
                new FieldValueMetaData(TType.STRING)));
        tmpMap.put(_Fields.CALLBACK_ADDR, new FieldMetaData("callbackAddr", TFieldRequirementType.REQUIRED,
                new FieldValueMetaData(TType.STRING)));
        tmpMap.put(_Fields.SIGN, new FieldMetaData("sign", TFieldRequirementType.REQUIRED, new FieldValueMetaData(
                TType.STRING)));
        tmpMap.put(_Fields.gb_CHANNEL_ID, new FieldMetaData("gbChannelId", TFieldRequirementType.OPTIONAL,
                new FieldValueMetaData(TType.I64)));
        tmpMap.put(_Fields.CONSUME_TARGET_PRODUCT, new FieldMetaData("consumeTargetProduct",
                TFieldRequirementType.OPTIONAL, new FieldValueMetaData(TType.STRING)));
        tmpMap.put(_Fields.ADD_MONEY_ORDER_ID, new FieldMetaData("addMoneyOrderId", TFieldRequirementType.OPTIONAL,
                new FieldValueMetaData(TType.STRING)));
        metaDataMap = Collections.unmodifiableMap(tmpMap);
        FieldMetaData.addStructMetaDataMap(PayMoneyRequest2.class, metaDataMap);
    }

    public PayMoneyRequest2() {
        this.gbChannelId = 0L;

        this.consumeTargetProduct = "";

        this.addMoneyOrderId = "";

    }

    public PayMoneyRequest2(long gbuid, String orderId, int moneyType, String money, String product, String payTime,
            String userIp, String goodsName, String description, String callbackAddr, String sign) {
        this();
        this.gbuid = gbuid;
        setgbuidIsSet(true);
        this.orderId = orderId;
        this.moneyType = moneyType;
        setMoneyTypeIsSet(true);
        this.money = money;
        this.product = product;
        this.payTime = payTime;
        this.userIp = userIp;
        this.goodsName = goodsName;
        this.description = description;
        this.callbackAddr = callbackAddr;
        this.sign = sign;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public PayMoneyRequest2(PayMoneyRequest2 other) {
        __isset_bit_vector.clear();
        __isset_bit_vector.or(other.__isset_bit_vector);
        this.gbuid = other.gbuid;
        if (other.isSetOrderId()) {
            this.orderId = other.orderId;
        }
        this.moneyType = other.moneyType;
        if (other.isSetMoney()) {
            this.money = other.money;
        }
        if (other.isSetProduct()) {
            this.product = other.product;
        }
        if (other.isSetPayTime()) {
            this.payTime = other.payTime;
        }
        if (other.isSetUserIp()) {
            this.userIp = other.userIp;
        }
        if (other.isSetGoodsName()) {
            this.goodsName = other.goodsName;
        }
        if (other.isSetDescription()) {
            this.description = other.description;
        }
        if (other.isSetCallbackAddr()) {
            this.callbackAddr = other.callbackAddr;
        }
        if (other.isSetSign()) {
            this.sign = other.sign;
        }
        this.gbChannelId = other.gbChannelId;
        if (other.isSetConsumeTargetProduct()) {
            this.consumeTargetProduct = other.consumeTargetProduct;
        }
        if (other.isSetAddMoneyOrderId()) {
            this.addMoneyOrderId = other.addMoneyOrderId;
        }
    }

    public PayMoneyRequest2 deepCopy() {
        return new PayMoneyRequest2(this);
    }

    @Override
    public void clear() {
        setgbuidIsSet(false);
        this.gbuid = 0;
        this.orderId = null;
        setMoneyTypeIsSet(false);
        this.moneyType = 0;
        this.money = null;
        this.product = null;
        this.payTime = null;
        this.userIp = null;
        this.goodsName = null;
        this.description = null;
        this.callbackAddr = null;
        this.sign = null;
        this.gbChannelId = 0L;

        this.consumeTargetProduct = "";

        this.addMoneyOrderId = "";

    }

    /**
     * gbuid
     */
    public long getgbuid() {
        return this.gbuid;
    }

    /**
     * gbuid
     */
    public PayMoneyRequest2 setgbuid(long gbuid) {
        this.gbuid = gbuid;
        setgbuidIsSet(true);
        return this;
    }

    public void unsetgbuid() {
        __isset_bit_vector.clear(__gbUID_ISSET_ID);
    }

    /**
     * Returns true if field gbuid is set (has been asigned a value) and false
     * otherwise
     */
    public boolean isSetgbuid() {
        return __isset_bit_vector.get(__gbUID_ISSET_ID);
    }

    public void setgbuidIsSet(boolean value) {
        __isset_bit_vector.set(__gbUID_ISSET_ID, value);
    }

    /**
     * 业务方订单号
     */
    public String getOrderId() {
        return this.orderId;
    }

    /**
     * 业务方订单号
     */
    public PayMoneyRequest2 setOrderId(String orderId) {
        this.orderId = orderId;
        return this;
    }

    public void unsetOrderId() {
        this.orderId = null;
    }

    /**
     * Returns true if field orderId is set (has been asigned a value) and false
     * otherwise
     */
    public boolean isSetOrderId() {
        return this.orderId != null;
    }

    public void setOrderIdIsSet(boolean value) {
        if (!value) {
            this.orderId = null;
        }
    }

    /**
     * 货币类型
     */
    public int getMoneyType() {
        return this.moneyType;
    }

    /**
     * 货币类型
     */
    public PayMoneyRequest2 setMoneyType(int moneyType) {
        this.moneyType = moneyType;
        setMoneyTypeIsSet(true);
        return this;
    }

    public void unsetMoneyType() {
        __isset_bit_vector.clear(__MONEYTYPE_ISSET_ID);
    }

    /**
     * Returns true if field moneyType is set (has been asigned a value) and
     * false otherwise
     */
    public boolean isSetMoneyType() {
        return __isset_bit_vector.get(__MONEYTYPE_ISSET_ID);
    }

    public void setMoneyTypeIsSet(boolean value) {
        __isset_bit_vector.set(__MONEYTYPE_ISSET_ID, value);
    }

    /**
     * 扣除的多玩币，单位：元，最小单位：0.01元
     */
    public String getMoney() {
        return this.money;
    }

    /**
     * 扣除的多玩币，单位：元，最小单位：0.01元
     */
    public PayMoneyRequest2 setMoney(String money) {
        this.money = money;
        return this;
    }

    public void unsetMoney() {
        this.money = null;
    }

    /**
     * Returns true if field money is set (has been asigned a value) and false
     * otherwise
     */
    public boolean isSetMoney() {
        return this.money != null;
    }

    public void setMoneyIsSet(boolean value) {
        if (!value) {
            this.money = null;
        }
    }

    /**
     * 应用ID，比如gb音乐叫gbMUSIC
     */
    public String getProduct() {
        return this.product;
    }

    /**
     * 应用ID，比如gb音乐叫gbMUSIC
     */
    public PayMoneyRequest2 setProduct(String product) {
        this.product = product;
        return this;
    }

    public void unsetProduct() {
        this.product = null;
    }

    /**
     * Returns true if field product is set (has been asigned a value) and false
     * otherwise
     */
    public boolean isSetProduct() {
        return this.product != null;
    }

    public void setProductIsSet(boolean value) {
        if (!value) {
            this.product = null;
        }
    }

    /**
     * 扣除多玩币的时间
     */
    public String getPayTime() {
        return this.payTime;
    }

    /**
     * 扣除多玩币的时间
     */
    public PayMoneyRequest2 setPayTime(String payTime) {
        this.payTime = payTime;
        return this;
    }

    public void unsetPayTime() {
        this.payTime = null;
    }

    /**
     * Returns true if field payTime is set (has been asigned a value) and false
     * otherwise
     */
    public boolean isSetPayTime() {
        return this.payTime != null;
    }

    public void setPayTimeIsSet(boolean value) {
        if (!value) {
            this.payTime = null;
        }
    }

    /**
     * 用户客户端IP
     */
    public String getUserIp() {
        return this.userIp;
    }

    /**
     * 用户客户端IP
     */
    public PayMoneyRequest2 setUserIp(String userIp) {
        this.userIp = userIp;
        return this;
    }

    public void unsetUserIp() {
        this.userIp = null;
    }

    /**
     * Returns true if field userIp is set (has been asigned a value) and false
     * otherwise
     */
    public boolean isSetUserIp() {
        return this.userIp != null;
    }

    public void setUserIpIsSet(boolean value) {
        if (!value) {
            this.userIp = null;
        }
    }

    /**
     * 商品名称，最长50字符
     */
    public String getGoodsName() {
        return this.goodsName;
    }

    /**
     * 商品名称，最长50字符
     */
    public PayMoneyRequest2 setGoodsName(String goodsName) {
        this.goodsName = goodsName;
        return this;
    }

    public void unsetGoodsName() {
        this.goodsName = null;
    }

    /**
     * Returns true if field goodsName is set (has been asigned a value) and
     * false otherwise
     */
    public boolean isSetGoodsName() {
        return this.goodsName != null;
    }

    public void setGoodsNameIsSet(boolean value) {
        if (!value) {
            this.goodsName = null;
        }
    }

    /**
     * 描述，最长100个字符
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * 描述，最长100个字符
     */
    public PayMoneyRequest2 setDescription(String description) {
        this.description = description;
        return this;
    }

    public void unsetDescription() {
        this.description = null;
    }

    /**
     * Returns true if field description is set (has been asigned a value) and
     * false otherwise
     */
    public boolean isSetDescription() {
        return this.description != null;
    }

    public void setDescriptionIsSet(boolean value) {
        if (!value) {
            this.description = null;
        }
    }

    /**
     * 回调地址(格式"host:port")或http://
     */
    public String getCallbackAddr() {
        return this.callbackAddr;
    }

    /**
     * 回调地址(格式"host:port")或http://
     */
    public PayMoneyRequest2 setCallbackAddr(String callbackAddr) {
        this.callbackAddr = callbackAddr;
        return this;
    }

    public void unsetCallbackAddr() {
        this.callbackAddr = null;
    }

    /**
     * Returns true if field callbackAddr is set (has been asigned a value) and
     * false otherwise
     */
    public boolean isSetCallbackAddr() {
        return this.callbackAddr != null;
    }

    public void setCallbackAddrIsSet(boolean value) {
        if (!value) {
            this.callbackAddr = null;
        }
    }

    /**
     * md5校验码
     */
    public String getSign() {
        return this.sign;
    }

    /**
     * md5校验码
     */
    public PayMoneyRequest2 setSign(String sign) {
        this.sign = sign;
        return this;
    }

    public void unsetSign() {
        this.sign = null;
    }

    /**
     * Returns true if field sign is set (has been asigned a value) and false
     * otherwise
     */
    public boolean isSetSign() {
        return this.sign != null;
    }

    public void setSignIsSet(boolean value) {
        if (!value) {
            this.sign = null;
        }
    }

    /**
     * gb频道ID，兼容旧接口的参数，可以填0
     */
    public long getgbChannelId() {
        return this.gbChannelId;
    }

    /**
     * gb频道ID，兼容旧接口的参数，可以填0
     */
    public PayMoneyRequest2 setgbChannelId(long gbChannelId) {
        this.gbChannelId = gbChannelId;
        setgbChannelIdIsSet(true);
        return this;
    }

    public void unsetgbChannelId() {
        __isset_bit_vector.clear(__gbCHANNELID_ISSET_ID);
    }

    /**
     * Returns true if field gbChannelId is set (has been asigned a value) and
     * false otherwise
     */
    public boolean isSetgbChannelId() {
        return __isset_bit_vector.get(__gbCHANNELID_ISSET_ID);
    }

    public void setgbChannelIdIsSet(boolean value) {
        __isset_bit_vector.set(__gbCHANNELID_ISSET_ID, value);
    }

    /**
     * 消费到哪个产品里，最长20字符，一般等于""，像开放平台、充值中心这种业务，consumeTargetProduct=游戏/应用ID，
     */
    public String getConsumeTargetProduct() {
        return this.consumeTargetProduct;
    }

    /**
     * 消费到哪个产品里，最长20字符，一般等于""，像开放平台、充值中心这种业务，consumeTargetProduct=游戏/应用ID，
     */
    public PayMoneyRequest2 setConsumeTargetProduct(String consumeTargetProduct) {
        this.consumeTargetProduct = consumeTargetProduct;
        return this;
    }

    public void unsetConsumeTargetProduct() {
        this.consumeTargetProduct = null;
    }

    /**
     * Returns true if field consumeTargetProduct is set (has been asigned a
     * value) and false otherwise
     */
    public boolean isSetConsumeTargetProduct() {
        return this.consumeTargetProduct != null;
    }

    public void setConsumeTargetProductIsSet(boolean value) {
        if (!value) {
            this.consumeTargetProduct = null;
        }
    }

    /**
     * addMoney()时的产品订单ID，当提供此ID，并且这个ID实际存在时，不会返回弹窗确认授权
     */
    public String getAddMoneyOrderId() {
        return this.addMoneyOrderId;
    }

    /**
     * addMoney()时的产品订单ID，当提供此ID，并且这个ID实际存在时，不会返回弹窗确认授权
     */
    public PayMoneyRequest2 setAddMoneyOrderId(String addMoneyOrderId) {
        this.addMoneyOrderId = addMoneyOrderId;
        return this;
    }

    public void unsetAddMoneyOrderId() {
        this.addMoneyOrderId = null;
    }

    /**
     * Returns true if field addMoneyOrderId is set (has been asigned a value)
     * and false otherwise
     */
    public boolean isSetAddMoneyOrderId() {
        return this.addMoneyOrderId != null;
    }

    public void setAddMoneyOrderIdIsSet(boolean value) {
        if (!value) {
            this.addMoneyOrderId = null;
        }
    }

    public void setFieldValue(_Fields field, Object value) {
        switch (field) {
        case gbUID:
            if (value == null) {
                unsetgbuid();
            } else {
                setgbuid((Long) value);
            }
            break;

        case ORDER_ID:
            if (value == null) {
                unsetOrderId();
            } else {
                setOrderId((String) value);
            }
            break;

        case MONEY_TYPE:
            if (value == null) {
                unsetMoneyType();
            } else {
                setMoneyType((Integer) value);
            }
            break;

        case MONEY:
            if (value == null) {
                unsetMoney();
            } else {
                setMoney((String) value);
            }
            break;

        case PRODUCT:
            if (value == null) {
                unsetProduct();
            } else {
                setProduct((String) value);
            }
            break;

        case PAY_TIME:
            if (value == null) {
                unsetPayTime();
            } else {
                setPayTime((String) value);
            }
            break;

        case USER_IP:
            if (value == null) {
                unsetUserIp();
            } else {
                setUserIp((String) value);
            }
            break;

        case GOODS_NAME:
            if (value == null) {
                unsetGoodsName();
            } else {
                setGoodsName((String) value);
            }
            break;

        case DESCRIPTION:
            if (value == null) {
                unsetDescription();
            } else {
                setDescription((String) value);
            }
            break;

        case CALLBACK_ADDR:
            if (value == null) {
                unsetCallbackAddr();
            } else {
                setCallbackAddr((String) value);
            }
            break;

        case SIGN:
            if (value == null) {
                unsetSign();
            } else {
                setSign((String) value);
            }
            break;

        case gb_CHANNEL_ID:
            if (value == null) {
                unsetgbChannelId();
            } else {
                setgbChannelId((Long) value);
            }
            break;

        case CONSUME_TARGET_PRODUCT:
            if (value == null) {
                unsetConsumeTargetProduct();
            } else {
                setConsumeTargetProduct((String) value);
            }
            break;

        case ADD_MONEY_ORDER_ID:
            if (value == null) {
                unsetAddMoneyOrderId();
            } else {
                setAddMoneyOrderId((String) value);
            }
            break;

        }
    }

    public Object getFieldValue(_Fields field) {
        switch (field) {
        case gbUID:
            return new Long(getgbuid());

        case ORDER_ID:
            return getOrderId();

        case MONEY_TYPE:
            return new Integer(getMoneyType());

        case MONEY:
            return getMoney();

        case PRODUCT:
            return getProduct();

        case PAY_TIME:
            return getPayTime();

        case USER_IP:
            return getUserIp();

        case GOODS_NAME:
            return getGoodsName();

        case DESCRIPTION:
            return getDescription();

        case CALLBACK_ADDR:
            return getCallbackAddr();

        case SIGN:
            return getSign();

        case gb_CHANNEL_ID:
            return new Long(getgbChannelId());

        case CONSUME_TARGET_PRODUCT:
            return getConsumeTargetProduct();

        case ADD_MONEY_ORDER_ID:
            return getAddMoneyOrderId();

        }
        throw new IllegalStateException();
    }

    /**
     * Returns true if field corresponding to fieldID is set (has been asigned a
     * value) and false otherwise
     */
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new IllegalArgumentException();
        }

        switch (field) {
        case gbUID:
            return isSetgbuid();
        case ORDER_ID:
            return isSetOrderId();
        case MONEY_TYPE:
            return isSetMoneyType();
        case MONEY:
            return isSetMoney();
        case PRODUCT:
            return isSetProduct();
        case PAY_TIME:
            return isSetPayTime();
        case USER_IP:
            return isSetUserIp();
        case GOODS_NAME:
            return isSetGoodsName();
        case DESCRIPTION:
            return isSetDescription();
        case CALLBACK_ADDR:
            return isSetCallbackAddr();
        case SIGN:
            return isSetSign();
        case gb_CHANNEL_ID:
            return isSetgbChannelId();
        case CONSUME_TARGET_PRODUCT:
            return isSetConsumeTargetProduct();
        case ADD_MONEY_ORDER_ID:
            return isSetAddMoneyOrderId();
        }
        throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
        if (that == null)
            return false;
        if (that instanceof PayMoneyRequest2)
            return this.equals((PayMoneyRequest2) that);
        return false;
    }

    public boolean equals(PayMoneyRequest2 that) {
        if (that == null)
            return false;

        boolean this_present_gbuid = true;
        boolean that_present_gbuid = true;
        if (this_present_gbuid || that_present_gbuid) {
            if (!(this_present_gbuid && that_present_gbuid))
                return false;
            if (this.gbuid != that.gbuid)
                return false;
        }

        boolean this_present_orderId = true && this.isSetOrderId();
        boolean that_present_orderId = true && that.isSetOrderId();
        if (this_present_orderId || that_present_orderId) {
            if (!(this_present_orderId && that_present_orderId))
                return false;
            if (!this.orderId.equals(that.orderId))
                return false;
        }

        boolean this_present_moneyType = true;
        boolean that_present_moneyType = true;
        if (this_present_moneyType || that_present_moneyType) {
            if (!(this_present_moneyType && that_present_moneyType))
                return false;
            if (this.moneyType != that.moneyType)
                return false;
        }

        boolean this_present_money = true && this.isSetMoney();
        boolean that_present_money = true && that.isSetMoney();
        if (this_present_money || that_present_money) {
            if (!(this_present_money && that_present_money))
                return false;
            if (!this.money.equals(that.money))
                return false;
        }

        boolean this_present_product = true && this.isSetProduct();
        boolean that_present_product = true && that.isSetProduct();
        if (this_present_product || that_present_product) {
            if (!(this_present_product && that_present_product))
                return false;
            if (!this.product.equals(that.product))
                return false;
        }

        boolean this_present_payTime = true && this.isSetPayTime();
        boolean that_present_payTime = true && that.isSetPayTime();
        if (this_present_payTime || that_present_payTime) {
            if (!(this_present_payTime && that_present_payTime))
                return false;
            if (!this.payTime.equals(that.payTime))
                return false;
        }

        boolean this_present_userIp = true && this.isSetUserIp();
        boolean that_present_userIp = true && that.isSetUserIp();
        if (this_present_userIp || that_present_userIp) {
            if (!(this_present_userIp && that_present_userIp))
                return false;
            if (!this.userIp.equals(that.userIp))
                return false;
        }

        boolean this_present_goodsName = true && this.isSetGoodsName();
        boolean that_present_goodsName = true && that.isSetGoodsName();
        if (this_present_goodsName || that_present_goodsName) {
            if (!(this_present_goodsName && that_present_goodsName))
                return false;
            if (!this.goodsName.equals(that.goodsName))
                return false;
        }

        boolean this_present_description = true && this.isSetDescription();
        boolean that_present_description = true && that.isSetDescription();
        if (this_present_description || that_present_description) {
            if (!(this_present_description && that_present_description))
                return false;
            if (!this.description.equals(that.description))
                return false;
        }

        boolean this_present_callbackAddr = true && this.isSetCallbackAddr();
        boolean that_present_callbackAddr = true && that.isSetCallbackAddr();
        if (this_present_callbackAddr || that_present_callbackAddr) {
            if (!(this_present_callbackAddr && that_present_callbackAddr))
                return false;
            if (!this.callbackAddr.equals(that.callbackAddr))
                return false;
        }

        boolean this_present_sign = true && this.isSetSign();
        boolean that_present_sign = true && that.isSetSign();
        if (this_present_sign || that_present_sign) {
            if (!(this_present_sign && that_present_sign))
                return false;
            if (!this.sign.equals(that.sign))
                return false;
        }

        boolean this_present_gbChannelId = true && this.isSetgbChannelId();
        boolean that_present_gbChannelId = true && that.isSetgbChannelId();
        if (this_present_gbChannelId || that_present_gbChannelId) {
            if (!(this_present_gbChannelId && that_present_gbChannelId))
                return false;
            if (this.gbChannelId != that.gbChannelId)
                return false;
        }

        boolean this_present_consumeTargetProduct = true && this.isSetConsumeTargetProduct();
        boolean that_present_consumeTargetProduct = true && that.isSetConsumeTargetProduct();
        if (this_present_consumeTargetProduct || that_present_consumeTargetProduct) {
            if (!(this_present_consumeTargetProduct && that_present_consumeTargetProduct))
                return false;
            if (!this.consumeTargetProduct.equals(that.consumeTargetProduct))
                return false;
        }

        boolean this_present_addMoneyOrderId = true && this.isSetAddMoneyOrderId();
        boolean that_present_addMoneyOrderId = true && that.isSetAddMoneyOrderId();
        if (this_present_addMoneyOrderId || that_present_addMoneyOrderId) {
            if (!(this_present_addMoneyOrderId && that_present_addMoneyOrderId))
                return false;
            if (!this.addMoneyOrderId.equals(that.addMoneyOrderId))
                return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        return 0;
    }

    public int compareTo(PayMoneyRequest2 other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;
        PayMoneyRequest2 typedOther = (PayMoneyRequest2) other;

        lastComparison = Boolean.valueOf(isSetgbuid()).compareTo(typedOther.isSetgbuid());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetgbuid()) {
            lastComparison = TBaseHelper.compareTo(this.gbuid, typedOther.gbuid);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetOrderId()).compareTo(typedOther.isSetOrderId());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetOrderId()) {
            lastComparison = TBaseHelper.compareTo(this.orderId, typedOther.orderId);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetMoneyType()).compareTo(typedOther.isSetMoneyType());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetMoneyType()) {
            lastComparison = TBaseHelper.compareTo(this.moneyType, typedOther.moneyType);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetMoney()).compareTo(typedOther.isSetMoney());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetMoney()) {
            lastComparison = TBaseHelper.compareTo(this.money, typedOther.money);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetProduct()).compareTo(typedOther.isSetProduct());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetProduct()) {
            lastComparison = TBaseHelper.compareTo(this.product, typedOther.product);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetPayTime()).compareTo(typedOther.isSetPayTime());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetPayTime()) {
            lastComparison = TBaseHelper.compareTo(this.payTime, typedOther.payTime);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetUserIp()).compareTo(typedOther.isSetUserIp());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetUserIp()) {
            lastComparison = TBaseHelper.compareTo(this.userIp, typedOther.userIp);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetGoodsName()).compareTo(typedOther.isSetGoodsName());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetGoodsName()) {
            lastComparison = TBaseHelper.compareTo(this.goodsName, typedOther.goodsName);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetDescription()).compareTo(typedOther.isSetDescription());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetDescription()) {
            lastComparison = TBaseHelper.compareTo(this.description, typedOther.description);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetCallbackAddr()).compareTo(typedOther.isSetCallbackAddr());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetCallbackAddr()) {
            lastComparison = TBaseHelper.compareTo(this.callbackAddr, typedOther.callbackAddr);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetSign()).compareTo(typedOther.isSetSign());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetSign()) {
            lastComparison = TBaseHelper.compareTo(this.sign, typedOther.sign);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetgbChannelId()).compareTo(typedOther.isSetgbChannelId());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetgbChannelId()) {
            lastComparison = TBaseHelper.compareTo(this.gbChannelId, typedOther.gbChannelId);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetConsumeTargetProduct()).compareTo(typedOther.isSetConsumeTargetProduct());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetConsumeTargetProduct()) {
            lastComparison = TBaseHelper.compareTo(this.consumeTargetProduct, typedOther.consumeTargetProduct);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetAddMoneyOrderId()).compareTo(typedOther.isSetAddMoneyOrderId());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetAddMoneyOrderId()) {
            lastComparison = TBaseHelper.compareTo(this.addMoneyOrderId, typedOther.addMoneyOrderId);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    public void read(TProtocol iprot) throws TException {
        TField field;
        iprot.readStructBegin();
        while (true) {
            field = iprot.readFieldBegin();
            if (field.type == TType.STOP) {
                break;
            }
            switch (field.id) {
            case 1: // gbUID
                if (field.type == TType.I64) {
                    this.gbuid = iprot.readI64();
                    setgbuidIsSet(true);
                } else {
                    TProtocolUtil.skip(iprot, field.type);
                }
                break;
            case 2: // ORDER_ID
                if (field.type == TType.STRING) {
                    this.orderId = iprot.readString();
                } else {
                    TProtocolUtil.skip(iprot, field.type);
                }
                break;
            case 3: // MONEY_TYPE
                if (field.type == TType.I32) {
                    this.moneyType = iprot.readI32();
                    setMoneyTypeIsSet(true);
                } else {
                    TProtocolUtil.skip(iprot, field.type);
                }
                break;
            case 4: // MONEY
                if (field.type == TType.STRING) {
                    this.money = iprot.readString();
                } else {
                    TProtocolUtil.skip(iprot, field.type);
                }
                break;
            case 5: // PRODUCT
                if (field.type == TType.STRING) {
                    this.product = iprot.readString();
                } else {
                    TProtocolUtil.skip(iprot, field.type);
                }
                break;
            case 6: // PAY_TIME
                if (field.type == TType.STRING) {
                    this.payTime = iprot.readString();
                } else {
                    TProtocolUtil.skip(iprot, field.type);
                }
                break;
            case 7: // USER_IP
                if (field.type == TType.STRING) {
                    this.userIp = iprot.readString();
                } else {
                    TProtocolUtil.skip(iprot, field.type);
                }
                break;
            case 8: // GOODS_NAME
                if (field.type == TType.STRING) {
                    this.goodsName = iprot.readString();
                } else {
                    TProtocolUtil.skip(iprot, field.type);
                }
                break;
            case 9: // DESCRIPTION
                if (field.type == TType.STRING) {
                    this.description = iprot.readString();
                } else {
                    TProtocolUtil.skip(iprot, field.type);
                }
                break;
            case 10: // CALLBACK_ADDR
                if (field.type == TType.STRING) {
                    this.callbackAddr = iprot.readString();
                } else {
                    TProtocolUtil.skip(iprot, field.type);
                }
                break;
            case 11: // SIGN
                if (field.type == TType.STRING) {
                    this.sign = iprot.readString();
                } else {
                    TProtocolUtil.skip(iprot, field.type);
                }
                break;
            case 12: // gb_CHANNEL_ID
                if (field.type == TType.I64) {
                    this.gbChannelId = iprot.readI64();
                    setgbChannelIdIsSet(true);
                } else {
                    TProtocolUtil.skip(iprot, field.type);
                }
                break;
            case 13: // CONSUME_TARGET_PRODUCT
                if (field.type == TType.STRING) {
                    this.consumeTargetProduct = iprot.readString();
                } else {
                    TProtocolUtil.skip(iprot, field.type);
                }
                break;
            case 14: // ADD_MONEY_ORDER_ID
                if (field.type == TType.STRING) {
                    this.addMoneyOrderId = iprot.readString();
                } else {
                    TProtocolUtil.skip(iprot, field.type);
                }
                break;
            default:
                TProtocolUtil.skip(iprot, field.type);
            }
            iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked
        // in the validate method
        if (!isSetgbuid()) {
            throw new TProtocolException("Required field 'gbuid' was not found in serialized data! Struct: "
                    + toString());
        }
        if (!isSetMoneyType()) {
            throw new TProtocolException("Required field 'moneyType' was not found in serialized data! Struct: "
                    + toString());
        }
        validate();
    }

    public void write(TProtocol oprot) throws TException {
        validate();

        oprot.writeStructBegin(STRUCT_DESC);
        oprot.writeFieldBegin(gbUID_FIELD_DESC);
        oprot.writeI64(this.gbuid);
        oprot.writeFieldEnd();
        if (this.orderId != null) {
            oprot.writeFieldBegin(ORDER_ID_FIELD_DESC);
            oprot.writeString(this.orderId);
            oprot.writeFieldEnd();
        }
        oprot.writeFieldBegin(MONEY_TYPE_FIELD_DESC);
        oprot.writeI32(this.moneyType);
        oprot.writeFieldEnd();
        if (this.money != null) {
            oprot.writeFieldBegin(MONEY_FIELD_DESC);
            oprot.writeString(this.money);
            oprot.writeFieldEnd();
        }
        if (this.product != null) {
            oprot.writeFieldBegin(PRODUCT_FIELD_DESC);
            oprot.writeString(this.product);
            oprot.writeFieldEnd();
        }
        if (this.payTime != null) {
            oprot.writeFieldBegin(PAY_TIME_FIELD_DESC);
            oprot.writeString(this.payTime);
            oprot.writeFieldEnd();
        }
        if (this.userIp != null) {
            oprot.writeFieldBegin(USER_IP_FIELD_DESC);
            oprot.writeString(this.userIp);
            oprot.writeFieldEnd();
        }
        if (this.goodsName != null) {
            oprot.writeFieldBegin(GOODS_NAME_FIELD_DESC);
            oprot.writeString(this.goodsName);
            oprot.writeFieldEnd();
        }
        if (this.description != null) {
            oprot.writeFieldBegin(DESCRIPTION_FIELD_DESC);
            oprot.writeString(this.description);
            oprot.writeFieldEnd();
        }
        if (this.callbackAddr != null) {
            oprot.writeFieldBegin(CALLBACK_ADDR_FIELD_DESC);
            oprot.writeString(this.callbackAddr);
            oprot.writeFieldEnd();
        }
        if (this.sign != null) {
            oprot.writeFieldBegin(SIGN_FIELD_DESC);
            oprot.writeString(this.sign);
            oprot.writeFieldEnd();
        }
        if (isSetgbChannelId()) {
            oprot.writeFieldBegin(gb_CHANNEL_ID_FIELD_DESC);
            oprot.writeI64(this.gbChannelId);
            oprot.writeFieldEnd();
        }
        if (this.consumeTargetProduct != null) {
            if (isSetConsumeTargetProduct()) {
                oprot.writeFieldBegin(CONSUME_TARGET_PRODUCT_FIELD_DESC);
                oprot.writeString(this.consumeTargetProduct);
                oprot.writeFieldEnd();
            }
        }
        if (this.addMoneyOrderId != null) {
            if (isSetAddMoneyOrderId()) {
                oprot.writeFieldBegin(ADD_MONEY_ORDER_ID_FIELD_DESC);
                oprot.writeString(this.addMoneyOrderId);
                oprot.writeFieldEnd();
            }
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PayMoneyRequest2(");
        boolean first = true;

        sb.append("gbuid:");
        sb.append(this.gbuid);
        first = false;
        if (!first)
            sb.append(", ");
        sb.append("orderId:");
        if (this.orderId == null) {
            sb.append("null");
        } else {
            sb.append(this.orderId);
        }
        first = false;
        if (!first)
            sb.append(", ");
        sb.append("moneyType:");
        sb.append(this.moneyType);
        first = false;
        if (!first)
            sb.append(", ");
        sb.append("money:");
        if (this.money == null) {
            sb.append("null");
        } else {
            sb.append(this.money);
        }
        first = false;
        if (!first)
            sb.append(", ");
        sb.append("product:");
        if (this.product == null) {
            sb.append("null");
        } else {
            sb.append(this.product);
        }
        first = false;
        if (!first)
            sb.append(", ");
        sb.append("payTime:");
        if (this.payTime == null) {
            sb.append("null");
        } else {
            sb.append(this.payTime);
        }
        first = false;
        if (!first)
            sb.append(", ");
        sb.append("userIp:");
        if (this.userIp == null) {
            sb.append("null");
        } else {
            sb.append(this.userIp);
        }
        first = false;
        if (!first)
            sb.append(", ");
        sb.append("goodsName:");
        if (this.goodsName == null) {
            sb.append("null");
        } else {
            sb.append(this.goodsName);
        }
        first = false;
        if (!first)
            sb.append(", ");
        sb.append("description:");
        if (this.description == null) {
            sb.append("null");
        } else {
            sb.append(this.description);
        }
        first = false;
        if (!first)
            sb.append(", ");
        sb.append("callbackAddr:");
        if (this.callbackAddr == null) {
            sb.append("null");
        } else {
            sb.append(this.callbackAddr);
        }
        first = false;
        if (!first)
            sb.append(", ");
        sb.append("sign:");
        if (this.sign == null) {
            sb.append("null");
        } else {
            sb.append(this.sign);
        }
        first = false;
        if (isSetgbChannelId()) {
            if (!first)
                sb.append(", ");
            sb.append("gbChannelId:");
            sb.append(this.gbChannelId);
            first = false;
        }
        if (isSetConsumeTargetProduct()) {
            if (!first)
                sb.append(", ");
            sb.append("consumeTargetProduct:");
            if (this.consumeTargetProduct == null) {
                sb.append("null");
            } else {
                sb.append(this.consumeTargetProduct);
            }
            first = false;
        }
        if (isSetAddMoneyOrderId()) {
            if (!first)
                sb.append(", ");
            sb.append("addMoneyOrderId:");
            if (this.addMoneyOrderId == null) {
                sb.append("null");
            } else {
                sb.append(this.addMoneyOrderId);
            }
            first = false;
        }
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws TException {
        // check for required fields
        // alas, we cannot check 'gbuid' because it's a primitive and you chose
        // the non-beans generator.
        if (orderId == null) {
            throw new TProtocolException("Required field 'orderId' was not present! Struct: " + toString());
        }
        // alas, we cannot check 'moneyType' because it's a primitive and you
        // chose the non-beans generator.
        if (money == null) {
            throw new TProtocolException("Required field 'money' was not present! Struct: " + toString());
        }
        if (product == null) {
            throw new TProtocolException("Required field 'product' was not present! Struct: " + toString());
        }
        if (payTime == null) {
            throw new TProtocolException("Required field 'payTime' was not present! Struct: " + toString());
        }
        if (userIp == null) {
            throw new TProtocolException("Required field 'userIp' was not present! Struct: " + toString());
        }
        if (goodsName == null) {
            throw new TProtocolException("Required field 'goodsName' was not present! Struct: " + toString());
        }
        if (description == null) {
            throw new TProtocolException("Required field 'description' was not present! Struct: " + toString());
        }
        if (callbackAddr == null) {
            throw new TProtocolException("Required field 'callbackAddr' was not present! Struct: " + toString());
        }
        if (sign == null) {
            throw new TProtocolException("Required field 'sign' was not present! Struct: " + toString());
        }
    }

}
