package com.guzhi.pay.channel.unicom.cxf.productordermanage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-02-24T10:52:51.126+08:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://ws.ifdp.womusic.cn/", name = "ProductOrderManage")
@XmlSeeAlso({ObjectFactory.class})
public interface ProductOrderManage {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "buyProductWithVCode", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.BuyProductWithVCode")
    @WebMethod
    @ResponseWrapper(localName = "buyProductWithVCodeResponse", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.BuyProductWithVCodeResponse")
    public com.guzhi.pay.channel.unicom.cxf.productordermanage.Response buyProductWithVCode(
        @WebParam(name = "arg0", targetNamespace = "")
        com.guzhi.pay.channel.unicom.cxf.productordermanage.BuyProductWithVCodeEvt arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.guzhi.pay.channel.unicom.cxf.InextraInfo arg1
    ) throws ServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "subProductWithVCode", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.SubProductWithVCode")
    @WebMethod
    @ResponseWrapper(localName = "subProductWithVCodeResponse", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.SubProductWithVCodeResponse")
    public com.guzhi.pay.channel.unicom.cxf.productordermanage.SubProductResp subProductWithVCode(
        @WebParam(name = "arg0", targetNamespace = "")
        com.guzhi.pay.channel.unicom.cxf.productordermanage.SubProductWithVCodeEvt arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.guzhi.pay.channel.unicom.cxf.InextraInfo arg1
    ) throws ServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "preSubProductWithVCode", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.PreSubProductWithVCode")
    @WebMethod
    @ResponseWrapper(localName = "preSubProductWithVCodeResponse", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.PreSubProductWithVCodeResponse")
    public com.guzhi.pay.channel.unicom.cxf.productordermanage.SubProductResp preSubProductWithVCode(
        @WebParam(name = "arg0", targetNamespace = "")
        com.guzhi.pay.channel.unicom.cxf.productordermanage.SubProductWithVCodeEvt arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.guzhi.pay.channel.unicom.cxf.InextraInfo arg1
    ) throws ServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "unSubProduct", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.UnSubProduct")
    @WebMethod
    @ResponseWrapper(localName = "unSubProductResponse", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.UnSubProductResponse")
    public com.guzhi.pay.channel.unicom.cxf.productordermanage.Response unSubProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        com.guzhi.pay.channel.unicom.cxf.productordermanage.UnSubProductEvt arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.guzhi.pay.channel.unicom.cxf.InextraInfo arg1
    ) throws ServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "qryAvaProducts", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.QryAvaProducts")
    @WebMethod
    @ResponseWrapper(localName = "qryAvaProductsResponse", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.QryAvaProductsResponse")
    public com.guzhi.pay.channel.unicom.cxf.productordermanage.QryAvaProductsResp qryAvaProducts(
        @WebParam(name = "arg0", targetNamespace = "")
        com.guzhi.pay.channel.unicom.cxf.productordermanage.QryAvaProductsEvt arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.guzhi.pay.channel.unicom.cxf.InextraInfo arg1
    ) throws ServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "unSubProductWithVCode", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.UnSubProductWithVCode")
    @WebMethod
    @ResponseWrapper(localName = "unSubProductWithVCodeResponse", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.UnSubProductWithVCodeResponse")
    public com.guzhi.pay.channel.unicom.cxf.productordermanage.Response unSubProductWithVCode(
        @WebParam(name = "arg0", targetNamespace = "")
        com.guzhi.pay.channel.unicom.cxf.productordermanage.UnSubProductWithVCodeEvt arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.guzhi.pay.channel.unicom.cxf.InextraInfo arg1
    ) throws ServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "qrySubedProducts", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.QrySubedProducts")
    @WebMethod
    @ResponseWrapper(localName = "qrySubedProductsResponse", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.QrySubedProductsResponse")
    public com.guzhi.pay.channel.unicom.cxf.productordermanage.QrySubedProductsResp qrySubedProducts(
        @WebParam(name = "arg0", targetNamespace = "")
        com.guzhi.pay.channel.unicom.cxf.productordermanage.QrySubedProductsEvt arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.guzhi.pay.channel.unicom.cxf.InextraInfo arg1
    ) throws ServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "qryVacSubScriptionList", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.QryVacSubScriptionList")
    @WebMethod
    @ResponseWrapper(localName = "qryVacSubScriptionListResponse", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.QryVacSubScriptionListResponse")
    public com.guzhi.pay.channel.unicom.cxf.productordermanage.QryVacSubScriptionListResp qryVacSubScriptionList(
        @WebParam(name = "arg0", targetNamespace = "")
        com.guzhi.pay.channel.unicom.cxf.productordermanage.QryVacSubScriptionListEvt arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "subProduct", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.SubProduct")
    @WebMethod
    @ResponseWrapper(localName = "subProductResponse", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.SubProductResponse")
    public com.guzhi.pay.channel.unicom.cxf.productordermanage.SubProductResp subProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        com.guzhi.pay.channel.unicom.cxf.productordermanage.SubProductEvt arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.guzhi.pay.channel.unicom.cxf.InextraInfo arg1
    ) throws ServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "buyProduct", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.BuyProduct")
    @WebMethod
    @ResponseWrapper(localName = "buyProductResponse", targetNamespace = "http://ws.ifdp.womusic.cn/", className = "com.guzhi.pay.channel.unicom.cxf.productordermanage.BuyProductResponse")
    public com.guzhi.pay.channel.unicom.cxf.productordermanage.Response buyProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        com.guzhi.pay.channel.unicom.cxf.productordermanage.BuyProductEvt arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.guzhi.pay.channel.unicom.cxf.InextraInfo arg1
    ) throws ServiceException_Exception;
}
