package com.guzhi.pay.channel.unicom.cxf.productordermanage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-02-24T10:52:51.175+08:00
 * Generated source version: 2.7.10
 * 
 */
@WebServiceClient(name = "ProductOrderManageImplService", 
                  wsdlLocation = "http://58.254.132.140:8080/ifdp/services/ProductOrderManage?wsdl",
                  targetNamespace = "http://impl.ws.ifdp.womusic.cn/") 
public class ProductOrderManageImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.ifdp.womusic.cn/", "ProductOrderManageImplService");
    public final static QName ProductOrderManageImplPort = new QName("http://impl.ws.ifdp.womusic.cn/", "ProductOrderManageImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://58.254.132.140:8080/ifdp/services/ProductOrderManage?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProductOrderManageImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://58.254.132.140:8080/ifdp/services/ProductOrderManage?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProductOrderManageImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductOrderManageImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductOrderManageImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ProductOrderManage
     */
    @WebEndpoint(name = "ProductOrderManageImplPort")
    public ProductOrderManage getProductOrderManageImplPort() {
        return super.getPort(ProductOrderManageImplPort, ProductOrderManage.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductOrderManage
     */
    @WebEndpoint(name = "ProductOrderManageImplPort")
    public ProductOrderManage getProductOrderManageImplPort(WebServiceFeature... features) {
        return super.getPort(ProductOrderManageImplPort, ProductOrderManage.class, features);
    }

}
