-- MySQL Script generated by MySQL Workbench
-- Tue Feb 28 12:12:02 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema paymentDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `paymentDB` ;

-- -----------------------------------------------------
-- Schema paymentDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `paymentDB` DEFAULT CHARACTER SET latin1 ;
USE `paymentDB` ;

-- -----------------------------------------------------
-- Table `paymentDB`.`t_bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymentDB`.`t_bill` ;

CREATE TABLE IF NOT EXISTS `paymentDB`.`t_bill` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '唯一标识',
  `uuid` VARCHAR(19) NOT NULL COMMENT '用户uuid',
  `ord_no` VARCHAR(64) NOT NULL COMMENT '业务订单号',
  `money` INT(11) NOT NULL COMMENT '金额（正数-收入，负数-支出）',
  `time` BIGINT(18) NOT NULL COMMENT '时间',
  `type` TINYINT(1) NOT NULL COMMENT '类型（1-普通红包，2-等额红包，3-随机红包，4-打赏，5-抽奖）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `paymentDB`.`t_lotteries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymentDB`.`t_lotteries` ;

CREATE TABLE IF NOT EXISTS `paymentDB`.`t_lotteries` (
  `id` VARCHAR(64) NOT NULL DEFAULT '0' COMMENT '红包id',
  `title` VARCHAR(64) NOT NULL DEFAULT ' ' COMMENT '抽奖标题',
  `typ` INT(1) NOT NULL DEFAULT '0' COMMENT '0:全部\n1:男\n2:女',
  `winners` INT(11) NOT NULL DEFAULT '0' COMMENT '中奖人数',
  `tot_amt` INT(11) NOT NULL DEFAULT '0' COMMENT '抽奖总金额',
  `remain_amt` INT(11) NOT NULL DEFAULT '0' COMMENT '还未领奖金额',
  `status` INT(1) NOT NULL DEFAULT '0' COMMENT '抽奖状态\n1:未支付，2:领奖中\n3:领奖完成\n4:过期\n0:已删除',
  `remain_cnt` INT(11) NOT NULL DEFAULT '0' COMMENT '剩余多少个领奖包未领取',
  `uuid` VARCHAR(19) NOT NULL DEFAULT ' ' COMMENT '创建人',
  `crt_tm` BIGINT(18) NOT NULL COMMENT '创建时间',
  `upd_tm` BIGINT(18) NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `paymentDB`.`t_lottery_locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymentDB`.`t_lottery_locations` ;

CREATE TABLE IF NOT EXISTS `paymentDB`.`t_lottery_locations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `lottery_id` VARCHAR(64) NOT NULL COMMENT '抽奖包ID',
  `loc_cd` VARCHAR(16) NOT NULL DEFAULT ' ' COMMENT '位置编码',
  `loc_nm` VARCHAR(45) NOT NULL DEFAULT ' ' COMMENT '位置名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `paymentDB`.`t_red_receive`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymentDB`.`t_red_receive` ;

CREATE TABLE IF NOT EXISTS `paymentDB`.`t_red_receive` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '唯一标识',
  `ord_no` VARCHAR(64) NOT NULL COMMENT '业务订单号',
  `rece_uuid` VARCHAR(19) NOT NULL COMMENT '领取人uuid',
  `money` INT(11) NOT NULL COMMENT '领取金额（单位：分）',
  `rece_tm` BIGINT(18) NOT NULL COMMENT '领取时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_rec` (`ord_no` ASC, `rece_uuid` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `paymentDB`.`t_red_send`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymentDB`.`t_red_send` ;

CREATE TABLE IF NOT EXISTS `paymentDB`.`t_red_send` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '唯一标识',
  `ord_no` VARCHAR(64) NOT NULL COMMENT '业务订单号',
  `send_uuid` VARCHAR(19) NOT NULL COMMENT '发送者UUID',
  `type` TINYINT(1) NOT NULL COMMENT '红包类型（1-普通红包，2-等额群红包，3-随机群红包）',
  `tota_money` INT(10) NOT NULL COMMENT '总金额（单位：分）',
  `each_money` INT(10) NOT NULL COMMENT '单个金额（单位：分）',
  `tota_number` INT(10) NOT NULL COMMENT '总数量',
  `rece_money` INT(11) NOT NULL COMMENT '已领取金额（单位：分）',
  `rece_number` INT(11) NOT NULL COMMENT '已领取数量',
  `content` VARCHAR(100) NOT NULL COMMENT '描述',
  `send_tm` BIGINT(18) NOT NULL COMMENT '发送时间',
  `over_tm` BIGINT(18) NOT NULL COMMENT '过期时间',
  `pay_status` TINYINT(1) NOT NULL COMMENT '支付状态（0-未支付，1-已支付，2-支付异常）',
  `ref_status` TINYINT(1) NOT NULL COMMENT '红包过期是否已退款（1-是，0-否）',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `NewIndex1` (`ord_no` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `paymentDB`.`t_reward`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymentDB`.`t_reward` ;

CREATE TABLE IF NOT EXISTS `paymentDB`.`t_reward` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '唯一标识',
  `ord_no` VARCHAR(64) NOT NULL COMMENT '业务订单号',
  `send_uuid` VARCHAR(19) NOT NULL COMMENT '打赏者UUID',
  `rece_uuid` VARCHAR(19) NOT NULL COMMENT '领赏着UUID',
  `money` INT(11) NOT NULL COMMENT '打赏金额（单位：分）',
  `content` VARCHAR(100) NOT NULL COMMENT '描述',
  `send_tm` BIGINT(18) NOT NULL COMMENT '打赏时间',
  `pay_status` TINYINT(1) NOT NULL COMMENT '支付状态（0-未支付，1-已支付，2支付异常）',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `NewIndex1` (`ord_no` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `paymentDB`.`t_transaction_serial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymentDB`.`t_transaction_serial` ;

CREATE TABLE IF NOT EXISTS `paymentDB`.`t_transaction_serial` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(18) NOT NULL DEFAULT ' ' COMMENT '交易者uuid',
  `biz_ord_no` VARCHAR(64) NOT NULL DEFAULT ' ' COMMENT '业务订单号',
  `biz_typ` VARCHAR(1) NOT NULL DEFAULT ' ' COMMENT '业务类型：1:普通红包,2:等额群红包,3:随机群红包,4:打赏,5:抽奖',
  `amt` BIGINT(18) NOT NULL DEFAULT '0' COMMENT '交易金额',
  `ptf_sts` INT(11) NOT NULL DEFAULT '0' COMMENT '平台交易状态 0:无效，1：成功，2：失败',
  `ptf_msg` VARCHAR(45) NOT NULL DEFAULT ' ' COMMENT '平台状态描述',
  `trans_desc` VARCHAR(256) NOT NULL DEFAULT ' ' COMMENT '交易描述',
  `corg_ord_no` VARCHAR(64) NOT NULL DEFAULT ' ' COMMENT '银企订单号',
  `corg_sts` VARCHAR(10) NOT NULL DEFAULT ' ' COMMENT '银企状态',
  `corg_msg` VARCHAR(128) NOT NULL DEFAULT ' ' COMMENT '银企状态描述',
  `crt_tm` BIGINT(18) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `upd_tm` BIGINT(18) NOT NULL DEFAULT '0' COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `paymentDB`.`t_winners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymentDB`.`t_winners` ;

CREATE TABLE IF NOT EXISTS `paymentDB`.`t_winners` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(19) NOT NULL DEFAULT ' ' COMMENT '获奖人ID',
  `lottery_id` VARCHAR(64) NOT NULL COMMENT '抽奖包ID',
  `nick_nm` VARCHAR(45) NOT NULL DEFAULT ' ',
  `sex` INT(1) NOT NULL DEFAULT '0' COMMENT '0:女\n1:男',
  `bonus` INT(11) NOT NULL DEFAULT '0' COMMENT '奖金',
  `status` INT(1) NOT NULL DEFAULT '0' COMMENT '0:初始状态\n1:已领奖\n2:已过期',
  `crt_tm` BIGINT(18) NOT NULL COMMENT '红包创建时间',
  `accept_tm` BIGINT(18) NOT NULL COMMENT '领奖时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
