-- MySQL Script generated by MySQL Workbench
-- Wed Feb 22 17:02:44 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema paymentDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `paymentDB` ;

-- -----------------------------------------------------
-- Schema paymentDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `paymentDB` DEFAULT CHARACTER SET latin1 ;
USE `paymentDB` ;

-- -----------------------------------------------------
-- Table `paymentDB`.`t_red_send` 发红包
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymentDB`.`t_red_send` ;

CREATE TABLE IF NOT EXISTS `paymentDB`.`t_red_send` (
  `ord_no` VARCHAR(50) NOT NULL COMMENT '业务订单号',
  `send_uuid` BIGINT(18) NOT NULL COMMENT '发送者UUID',
  `red_type` TINYINT(1) NOT NULL COMMENT '红包类型（1-普通红包，2-等额群红包，3-随机群红包）',
  `tot_amount` INT(10) NOT NULL COMMENT '总金额（单位：分）',
  `any_amount` INT(10) NOT NULL COMMENT '单个金额（单位：分）',
  `num` INT(10) NOT NULL COMMENT '红包数量',
  `content` VARCHAR(100) NOT NULL COMMENT '描述',
  `send_tm` BIGINT(18) NOT NULL COMMENT '发送时间',
  `invalid_tm` BIGINT(18) NOT NULL COMMENT '失效时间',
  `rec_status` TINYINT(1) NOT NULL COMMENT '领取状态（0-不可领取，1-领取中，2-已结束）',
  `pay_status` TINYINT(1) NOT NULL COMMENT '支付状态（0-未支付，1-已支付，2-支付异常）',
  PRIMARY KEY (`ord_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `paymentDB`.`t_red_rec`  领红包
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymentDB`.`t_red_rec` ;

CREATE TABLE IF NOT EXISTS `paymentDB`.`t_red_rec` (
  `rec_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '唯一标识',
  `ord_no` VARCHAR(50) NOT NULL COMMENT '业务订单号',
  `rec_uuid` VARCHAR(18) NOT NULL COMMENT '领取人uuid',
  `amount` INT(11) NOT NULL COMMENT '领取金额（单位：分）',
  `rec_tm` BIGINT(18) NOT NULL COMMENT '领取时间',
  PRIMARY KEY (`rec_id`),
  UNIQUE INDEX `idx_rec` (`ord_no` ASC, `rec_uuid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `paymentDB`.`t_reward` 打赏
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymentDB`.`t_reward` ;

CREATE TABLE IF NOT EXISTS `paymentDB`.`t_reward` (
  `ord_no` VARCHAR(50) NOT NULL COMMENT '订单号',
  `rew_uuid` BIGINT(18) NOT NULL COMMENT '打赏者UUID',
  `rec_uuid` BIGINT(18) NOT NULL COMMENT '领赏着UUID',
  `amount` INT(11) NOT NULL COMMENT '打赏金额（单位：分）',
  `content` VARCHAR(100) NOT NULL COMMENT '描述',
  `rew_tm` BIGINT(18) NOT NULL COMMENT '打赏时间',
  `pay_status` TINYINT(1) NOT NULL COMMENT '支付状态（0-未支付，1-已支付，2支付异常）',
  PRIMARY KEY (`ord_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `paymentDB`.`t_tra_pay`  支付流水
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymentDB`.`t_tra_pay` ;

CREATE TABLE IF NOT EXISTS `paymentDB`.`t_tra_pay` (
  `tra_no` VARCHAR(30) NOT NULL COMMENT '交易订单号',
  `amount` INT(50) NOT NULL COMMENT '支付金额',
  `status` TINYINT(1) NOT NULL COMMENT '支付状态',
  `time` BIGINT(18) NOT NULL COMMENT '支付时间',
  `ord_no` VARCHAR(30) NOT NULL COMMENT '业务订单号',
  `rec_uid` VARCHAR(50) NOT NULL COMMENT '收款人id',
  `sign` VARCHAR(50) NOT NULL COMMENT '签名串',
  PRIMARY KEY (`tra_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `paymentDB`.`t_tra_transfer`  转账流水
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymentDB`.`t_tra_transfer` ;

CREATE TABLE IF NOT EXISTS `paymentDB`.`t_tra_transfer` (
  `tra_no` VARCHAR(11) NOT NULL COMMENT '交易订单号',
  `rec_uuid` BIGINT(18) NOT NULL COMMENT '收款人uuid',
  `amount` INT(11) NOT NULL COMMENT '转账金额(单位：分)',
  `tra_tm` BIGINT(18) NOT NULL COMMENT '转账时间',
  `ord_no` VARCHAR(50) NOT NULL COMMENT '业务订单号',
  `type` INT(1) NOT NULL COMMENT '转账类型（1-领红包转账，2-退款转账，3-打赏转账）',
  PRIMARY KEY (`tra_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `paymentDB`.`t_lotteries` 抽奖
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymentDB`.`t_lotteries` ;

CREATE TABLE IF NOT EXISTS `paymentDB`.`t_lotteries` (
  `id` VARCHAR(50) NOT NULL DEFAULT '0' COMMENT '红包id',
  `title` VARCHAR(45) NOT NULL DEFAULT ' ' COMMENT '抽奖标题',
  `typ` INT(1) NOT NULL DEFAULT '0' COMMENT '0:全部\n1:男\n2:女',
  `winners` INT(11) NOT NULL DEFAULT '0' COMMENT '中奖人数',
  `tot_amt` INT(11) NOT NULL DEFAULT '0' COMMENT '抽奖总金额',
  `remain_amt` INT(11) NOT NULL DEFAULT '0' COMMENT '还未领奖金额',
  `status` INT(1) NOT NULL DEFAULT '0' COMMENT '抽奖状态\n1:未支付，2:领奖中\n3:领奖完成\n4:过期\n0:已删除',
  `uuid` VARCHAR(18) NOT NULL DEFAULT ' ' COMMENT '创建人',
  `crt_tm` BIGINT(18) NOT NULL COMMENT '创建时间',
  `upd_tm` BIGINT(18) NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `paymentDB`.`t_lottery_locations` 抽奖地理位置
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymentDB`.`t_lottery_locations` ;

CREATE TABLE IF NOT EXISTS `paymentDB`.`t_lottery_locations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `lottery_id` VARCHAR(50) NOT NULL COMMENT '抽奖包ID',
  `loc_cd` VARCHAR(10) NOT NULL DEFAULT ' ' COMMENT '位置编码',
  `loc_nm` VARCHAR(45) NOT NULL DEFAULT ' ' COMMENT '位置名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `paymentDB`.`t_winners` 中奖人名单
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymentDB`.`t_winners` ;

CREATE TABLE IF NOT EXISTS `paymentDB`.`t_winners` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(18) NOT NULL DEFAULT ' ' COMMENT '获奖人ID',
  `lottery_id` VARCHAR(50) NOT NULL COMMENT '抽奖包ID',
  `sex` INT(11) NOT NULL DEFAULT '0' COMMENT '0:女\n1:男',
  `bonus` INT(11) NOT NULL DEFAULT '0' COMMENT '奖金',
  `status` INT(11) NOT NULL DEFAULT '0' COMMENT '0:初始状态\n1:已领奖\n2:已过期',
  `crt_tm` BIGINT(18) NOT NULL COMMENT '红包创建时间',
  `accept_tm` BIGINT(18) NOT NULL COMMENT '领奖时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;