// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package com.blemobi.sep.probuf;

public final class PaymentProtos {
  private PaymentProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PWeixinPayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.PWeixinPay)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string appid = 1;</code>
     *
     * <pre>
     * 应用ID
     * </pre>
     */
    java.lang.String getAppid();
    /**
     * <code>optional string appid = 1;</code>
     *
     * <pre>
     * 应用ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getAppidBytes();

    /**
     * <code>optional string partnerid = 2;</code>
     *
     * <pre>
     * 商户号
     * </pre>
     */
    java.lang.String getPartnerid();
    /**
     * <code>optional string partnerid = 2;</code>
     *
     * <pre>
     * 商户号
     * </pre>
     */
    com.google.protobuf.ByteString
        getPartneridBytes();

    /**
     * <code>optional string noncestr = 3;</code>
     *
     * <pre>
     * 随机串
     * </pre>
     */
    java.lang.String getNoncestr();
    /**
     * <code>optional string noncestr = 3;</code>
     *
     * <pre>
     * 随机串
     * </pre>
     */
    com.google.protobuf.ByteString
        getNoncestrBytes();

    /**
     * <code>optional string timestamp = 4;</code>
     *
     * <pre>
     * 时间戳
     * </pre>
     */
    java.lang.String getTimestamp();
    /**
     * <code>optional string timestamp = 4;</code>
     *
     * <pre>
     * 时间戳
     * </pre>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <code>optional string prepayid = 5;</code>
     *
     * <pre>
     * 预支付串
     * </pre>
     */
    java.lang.String getPrepayid();
    /**
     * <code>optional string prepayid = 5;</code>
     *
     * <pre>
     * 预支付串
     * </pre>
     */
    com.google.protobuf.ByteString
        getPrepayidBytes();

    /**
     * <code>optional string package = 6;</code>
     *
     * <pre>
     * 订单信息串
     * </pre>
     */
    java.lang.String getPackage();
    /**
     * <code>optional string package = 6;</code>
     *
     * <pre>
     * 订单信息串
     * </pre>
     */
    com.google.protobuf.ByteString
        getPackageBytes();

    /**
     * <code>optional string sign = 7;</code>
     *
     * <pre>
     * 签名串
     * </pre>
     */
    java.lang.String getSign();
    /**
     * <code>optional string sign = 7;</code>
     *
     * <pre>
     * 签名串
     * </pre>
     */
    com.google.protobuf.ByteString
        getSignBytes();

    /**
     * <code>optional string orderNo = 8;</code>
     *
     * <pre>
     * 订单的编号
     * </pre>
     */
    java.lang.String getOrderNo();
    /**
     * <code>optional string orderNo = 8;</code>
     *
     * <pre>
     * 订单的编号
     * </pre>
     */
    com.google.protobuf.ByteString
        getOrderNoBytes();
  }
  /**
   * Protobuf type {@code common.PWeixinPay}
   */
  public  static final class PWeixinPay extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:common.PWeixinPay)
      PWeixinPayOrBuilder {
    // Use PWeixinPay.newBuilder() to construct.
    private PWeixinPay(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private PWeixinPay() {
      appid_ = "";
      partnerid_ = "";
      noncestr_ = "";
      timestamp_ = "";
      prepayid_ = "";
      package_ = "";
      sign_ = "";
      orderNo_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PWeixinPay(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();

              appid_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();

              partnerid_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();

              noncestr_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();

              timestamp_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();

              prepayid_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();

              package_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();

              sign_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();

              orderNo_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blemobi.sep.probuf.PaymentProtos.internal_static_common_PWeixinPay_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blemobi.sep.probuf.PaymentProtos.internal_static_common_PWeixinPay_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blemobi.sep.probuf.PaymentProtos.PWeixinPay.class, com.blemobi.sep.probuf.PaymentProtos.PWeixinPay.Builder.class);
    }

    public static final int APPID_FIELD_NUMBER = 1;
    private volatile java.lang.Object appid_;
    /**
     * <code>optional string appid = 1;</code>
     *
     * <pre>
     * 应用ID
     * </pre>
     */
    public java.lang.String getAppid() {
      java.lang.Object ref = appid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string appid = 1;</code>
     *
     * <pre>
     * 应用ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAppidBytes() {
      java.lang.Object ref = appid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARTNERID_FIELD_NUMBER = 2;
    private volatile java.lang.Object partnerid_;
    /**
     * <code>optional string partnerid = 2;</code>
     *
     * <pre>
     * 商户号
     * </pre>
     */
    public java.lang.String getPartnerid() {
      java.lang.Object ref = partnerid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          partnerid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string partnerid = 2;</code>
     *
     * <pre>
     * 商户号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPartneridBytes() {
      java.lang.Object ref = partnerid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partnerid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NONCESTR_FIELD_NUMBER = 3;
    private volatile java.lang.Object noncestr_;
    /**
     * <code>optional string noncestr = 3;</code>
     *
     * <pre>
     * 随机串
     * </pre>
     */
    public java.lang.String getNoncestr() {
      java.lang.Object ref = noncestr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          noncestr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string noncestr = 3;</code>
     *
     * <pre>
     * 随机串
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNoncestrBytes() {
      java.lang.Object ref = noncestr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        noncestr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private volatile java.lang.Object timestamp_;
    /**
     * <code>optional string timestamp = 4;</code>
     *
     * <pre>
     * 时间戳
     * </pre>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timestamp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string timestamp = 4;</code>
     *
     * <pre>
     * 时间戳
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PREPAYID_FIELD_NUMBER = 5;
    private volatile java.lang.Object prepayid_;
    /**
     * <code>optional string prepayid = 5;</code>
     *
     * <pre>
     * 预支付串
     * </pre>
     */
    public java.lang.String getPrepayid() {
      java.lang.Object ref = prepayid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          prepayid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string prepayid = 5;</code>
     *
     * <pre>
     * 预支付串
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPrepayidBytes() {
      java.lang.Object ref = prepayid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prepayid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PACKAGE_FIELD_NUMBER = 6;
    private volatile java.lang.Object package_;
    /**
     * <code>optional string package = 6;</code>
     *
     * <pre>
     * 订单信息串
     * </pre>
     */
    public java.lang.String getPackage() {
      java.lang.Object ref = package_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          package_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string package = 6;</code>
     *
     * <pre>
     * 订单信息串
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPackageBytes() {
      java.lang.Object ref = package_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        package_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGN_FIELD_NUMBER = 7;
    private volatile java.lang.Object sign_;
    /**
     * <code>optional string sign = 7;</code>
     *
     * <pre>
     * 签名串
     * </pre>
     */
    public java.lang.String getSign() {
      java.lang.Object ref = sign_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sign_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sign = 7;</code>
     *
     * <pre>
     * 签名串
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      java.lang.Object ref = sign_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERNO_FIELD_NUMBER = 8;
    private volatile java.lang.Object orderNo_;
    /**
     * <code>optional string orderNo = 8;</code>
     *
     * <pre>
     * 订单的编号
     * </pre>
     */
    public java.lang.String getOrderNo() {
      java.lang.Object ref = orderNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          orderNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string orderNo = 8;</code>
     *
     * <pre>
     * 订单的编号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOrderNoBytes() {
      java.lang.Object ref = orderNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAppidBytes().isEmpty()) {
        output.writeBytes(1, getAppidBytes());
      }
      if (!getPartneridBytes().isEmpty()) {
        output.writeBytes(2, getPartneridBytes());
      }
      if (!getNoncestrBytes().isEmpty()) {
        output.writeBytes(3, getNoncestrBytes());
      }
      if (!getTimestampBytes().isEmpty()) {
        output.writeBytes(4, getTimestampBytes());
      }
      if (!getPrepayidBytes().isEmpty()) {
        output.writeBytes(5, getPrepayidBytes());
      }
      if (!getPackageBytes().isEmpty()) {
        output.writeBytes(6, getPackageBytes());
      }
      if (!getSignBytes().isEmpty()) {
        output.writeBytes(7, getSignBytes());
      }
      if (!getOrderNoBytes().isEmpty()) {
        output.writeBytes(8, getOrderNoBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAppidBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAppidBytes());
      }
      if (!getPartneridBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPartneridBytes());
      }
      if (!getNoncestrBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNoncestrBytes());
      }
      if (!getTimestampBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTimestampBytes());
      }
      if (!getPrepayidBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getPrepayidBytes());
      }
      if (!getPackageBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getPackageBytes());
      }
      if (!getSignBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getSignBytes());
      }
      if (!getOrderNoBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getOrderNoBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.blemobi.sep.probuf.PaymentProtos.PWeixinPay parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PWeixinPay parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PWeixinPay parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PWeixinPay parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PWeixinPay parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PWeixinPay parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PWeixinPay parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PWeixinPay parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PWeixinPay parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PWeixinPay parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blemobi.sep.probuf.PaymentProtos.PWeixinPay prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.PWeixinPay}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.PWeixinPay)
        com.blemobi.sep.probuf.PaymentProtos.PWeixinPayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blemobi.sep.probuf.PaymentProtos.internal_static_common_PWeixinPay_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blemobi.sep.probuf.PaymentProtos.internal_static_common_PWeixinPay_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blemobi.sep.probuf.PaymentProtos.PWeixinPay.class, com.blemobi.sep.probuf.PaymentProtos.PWeixinPay.Builder.class);
      }

      // Construct using com.blemobi.sep.probuf.PaymentProtos.PWeixinPay.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        appid_ = "";

        partnerid_ = "";

        noncestr_ = "";

        timestamp_ = "";

        prepayid_ = "";

        package_ = "";

        sign_ = "";

        orderNo_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blemobi.sep.probuf.PaymentProtos.internal_static_common_PWeixinPay_descriptor;
      }

      public com.blemobi.sep.probuf.PaymentProtos.PWeixinPay getDefaultInstanceForType() {
        return com.blemobi.sep.probuf.PaymentProtos.PWeixinPay.getDefaultInstance();
      }

      public com.blemobi.sep.probuf.PaymentProtos.PWeixinPay build() {
        com.blemobi.sep.probuf.PaymentProtos.PWeixinPay result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.blemobi.sep.probuf.PaymentProtos.PWeixinPay buildPartial() {
        com.blemobi.sep.probuf.PaymentProtos.PWeixinPay result = new com.blemobi.sep.probuf.PaymentProtos.PWeixinPay(this);
        result.appid_ = appid_;
        result.partnerid_ = partnerid_;
        result.noncestr_ = noncestr_;
        result.timestamp_ = timestamp_;
        result.prepayid_ = prepayid_;
        result.package_ = package_;
        result.sign_ = sign_;
        result.orderNo_ = orderNo_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blemobi.sep.probuf.PaymentProtos.PWeixinPay) {
          return mergeFrom((com.blemobi.sep.probuf.PaymentProtos.PWeixinPay)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blemobi.sep.probuf.PaymentProtos.PWeixinPay other) {
        if (other == com.blemobi.sep.probuf.PaymentProtos.PWeixinPay.getDefaultInstance()) return this;
        if (!other.getAppid().isEmpty()) {
          appid_ = other.appid_;
          onChanged();
        }
        if (!other.getPartnerid().isEmpty()) {
          partnerid_ = other.partnerid_;
          onChanged();
        }
        if (!other.getNoncestr().isEmpty()) {
          noncestr_ = other.noncestr_;
          onChanged();
        }
        if (!other.getTimestamp().isEmpty()) {
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (!other.getPrepayid().isEmpty()) {
          prepayid_ = other.prepayid_;
          onChanged();
        }
        if (!other.getPackage().isEmpty()) {
          package_ = other.package_;
          onChanged();
        }
        if (!other.getSign().isEmpty()) {
          sign_ = other.sign_;
          onChanged();
        }
        if (!other.getOrderNo().isEmpty()) {
          orderNo_ = other.orderNo_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blemobi.sep.probuf.PaymentProtos.PWeixinPay parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blemobi.sep.probuf.PaymentProtos.PWeixinPay) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object appid_ = "";
      /**
       * <code>optional string appid = 1;</code>
       *
       * <pre>
       * 应用ID
       * </pre>
       */
      public java.lang.String getAppid() {
        java.lang.Object ref = appid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            appid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string appid = 1;</code>
       *
       * <pre>
       * 应用ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAppidBytes() {
        java.lang.Object ref = appid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string appid = 1;</code>
       *
       * <pre>
       * 应用ID
       * </pre>
       */
      public Builder setAppid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string appid = 1;</code>
       *
       * <pre>
       * 应用ID
       * </pre>
       */
      public Builder clearAppid() {
        
        appid_ = getDefaultInstance().getAppid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string appid = 1;</code>
       *
       * <pre>
       * 应用ID
       * </pre>
       */
      public Builder setAppidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object partnerid_ = "";
      /**
       * <code>optional string partnerid = 2;</code>
       *
       * <pre>
       * 商户号
       * </pre>
       */
      public java.lang.String getPartnerid() {
        java.lang.Object ref = partnerid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            partnerid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string partnerid = 2;</code>
       *
       * <pre>
       * 商户号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPartneridBytes() {
        java.lang.Object ref = partnerid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          partnerid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string partnerid = 2;</code>
       *
       * <pre>
       * 商户号
       * </pre>
       */
      public Builder setPartnerid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        partnerid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string partnerid = 2;</code>
       *
       * <pre>
       * 商户号
       * </pre>
       */
      public Builder clearPartnerid() {
        
        partnerid_ = getDefaultInstance().getPartnerid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string partnerid = 2;</code>
       *
       * <pre>
       * 商户号
       * </pre>
       */
      public Builder setPartneridBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        partnerid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object noncestr_ = "";
      /**
       * <code>optional string noncestr = 3;</code>
       *
       * <pre>
       * 随机串
       * </pre>
       */
      public java.lang.String getNoncestr() {
        java.lang.Object ref = noncestr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            noncestr_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string noncestr = 3;</code>
       *
       * <pre>
       * 随机串
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNoncestrBytes() {
        java.lang.Object ref = noncestr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          noncestr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string noncestr = 3;</code>
       *
       * <pre>
       * 随机串
       * </pre>
       */
      public Builder setNoncestr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        noncestr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string noncestr = 3;</code>
       *
       * <pre>
       * 随机串
       * </pre>
       */
      public Builder clearNoncestr() {
        
        noncestr_ = getDefaultInstance().getNoncestr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string noncestr = 3;</code>
       *
       * <pre>
       * 随机串
       * </pre>
       */
      public Builder setNoncestrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        noncestr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <code>optional string timestamp = 4;</code>
       *
       * <pre>
       * 时间戳
       * </pre>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            timestamp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string timestamp = 4;</code>
       *
       * <pre>
       * 时间戳
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string timestamp = 4;</code>
       *
       * <pre>
       * 时间戳
       * </pre>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string timestamp = 4;</code>
       *
       * <pre>
       * 时间戳
       * </pre>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string timestamp = 4;</code>
       *
       * <pre>
       * 时间戳
       * </pre>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timestamp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object prepayid_ = "";
      /**
       * <code>optional string prepayid = 5;</code>
       *
       * <pre>
       * 预支付串
       * </pre>
       */
      public java.lang.String getPrepayid() {
        java.lang.Object ref = prepayid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            prepayid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string prepayid = 5;</code>
       *
       * <pre>
       * 预支付串
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPrepayidBytes() {
        java.lang.Object ref = prepayid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          prepayid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string prepayid = 5;</code>
       *
       * <pre>
       * 预支付串
       * </pre>
       */
      public Builder setPrepayid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        prepayid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string prepayid = 5;</code>
       *
       * <pre>
       * 预支付串
       * </pre>
       */
      public Builder clearPrepayid() {
        
        prepayid_ = getDefaultInstance().getPrepayid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string prepayid = 5;</code>
       *
       * <pre>
       * 预支付串
       * </pre>
       */
      public Builder setPrepayidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        prepayid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object package_ = "";
      /**
       * <code>optional string package = 6;</code>
       *
       * <pre>
       * 订单信息串
       * </pre>
       */
      public java.lang.String getPackage() {
        java.lang.Object ref = package_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            package_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string package = 6;</code>
       *
       * <pre>
       * 订单信息串
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPackageBytes() {
        java.lang.Object ref = package_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          package_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string package = 6;</code>
       *
       * <pre>
       * 订单信息串
       * </pre>
       */
      public Builder setPackage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        package_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string package = 6;</code>
       *
       * <pre>
       * 订单信息串
       * </pre>
       */
      public Builder clearPackage() {
        
        package_ = getDefaultInstance().getPackage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string package = 6;</code>
       *
       * <pre>
       * 订单信息串
       * </pre>
       */
      public Builder setPackageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        package_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sign_ = "";
      /**
       * <code>optional string sign = 7;</code>
       *
       * <pre>
       * 签名串
       * </pre>
       */
      public java.lang.String getSign() {
        java.lang.Object ref = sign_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sign_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sign = 7;</code>
       *
       * <pre>
       * 签名串
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSignBytes() {
        java.lang.Object ref = sign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sign = 7;</code>
       *
       * <pre>
       * 签名串
       * </pre>
       */
      public Builder setSign(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sign = 7;</code>
       *
       * <pre>
       * 签名串
       * </pre>
       */
      public Builder clearSign() {
        
        sign_ = getDefaultInstance().getSign();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sign = 7;</code>
       *
       * <pre>
       * 签名串
       * </pre>
       */
      public Builder setSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sign_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object orderNo_ = "";
      /**
       * <code>optional string orderNo = 8;</code>
       *
       * <pre>
       * 订单的编号
       * </pre>
       */
      public java.lang.String getOrderNo() {
        java.lang.Object ref = orderNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            orderNo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string orderNo = 8;</code>
       *
       * <pre>
       * 订单的编号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOrderNoBytes() {
        java.lang.Object ref = orderNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string orderNo = 8;</code>
       *
       * <pre>
       * 订单的编号
       * </pre>
       */
      public Builder setOrderNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderNo = 8;</code>
       *
       * <pre>
       * 订单的编号
       * </pre>
       */
      public Builder clearOrderNo() {
        
        orderNo_ = getDefaultInstance().getOrderNo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderNo = 8;</code>
       *
       * <pre>
       * 订单的编号
       * </pre>
       */
      public Builder setOrderNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderNo_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:common.PWeixinPay)
    }

    // @@protoc_insertion_point(class_scope:common.PWeixinPay)
    private static final com.blemobi.sep.probuf.PaymentProtos.PWeixinPay DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blemobi.sep.probuf.PaymentProtos.PWeixinPay();
    }

    public static com.blemobi.sep.probuf.PaymentProtos.PWeixinPay getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<PWeixinPay> PARSER =
        new com.google.protobuf.AbstractParser<PWeixinPay>() {
      public PWeixinPay parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PWeixinPay(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PWeixinPay> getParserForType() {
      return PARSER;
    }

    public com.blemobi.sep.probuf.PaymentProtos.PWeixinPay getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PAlipayOrderInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.PAlipayOrderInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string orderNo = 1;</code>
     *
     * <pre>
     * 订单的编号
     * </pre>
     */
    java.lang.String getOrderNo();
    /**
     * <code>optional string orderNo = 1;</code>
     *
     * <pre>
     * 订单的编号
     * </pre>
     */
    com.google.protobuf.ByteString
        getOrderNoBytes();

    /**
     * <code>optional string payInfo = 2;</code>
     *
     * <pre>
     * 订单的签名信息
     * </pre>
     */
    java.lang.String getPayInfo();
    /**
     * <code>optional string payInfo = 2;</code>
     *
     * <pre>
     * 订单的签名信息
     * </pre>
     */
    com.google.protobuf.ByteString
        getPayInfoBytes();
  }
  /**
   * Protobuf type {@code common.PAlipayOrderInfo}
   *
   * <pre>
   * 生成订单的编号和订单的签名信息
   * </pre>
   */
  public  static final class PAlipayOrderInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:common.PAlipayOrderInfo)
      PAlipayOrderInfoOrBuilder {
    // Use PAlipayOrderInfo.newBuilder() to construct.
    private PAlipayOrderInfo(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private PAlipayOrderInfo() {
      orderNo_ = "";
      payInfo_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PAlipayOrderInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();

              orderNo_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();

              payInfo_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blemobi.sep.probuf.PaymentProtos.internal_static_common_PAlipayOrderInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blemobi.sep.probuf.PaymentProtos.internal_static_common_PAlipayOrderInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo.class, com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo.Builder.class);
    }

    public static final int ORDERNO_FIELD_NUMBER = 1;
    private volatile java.lang.Object orderNo_;
    /**
     * <code>optional string orderNo = 1;</code>
     *
     * <pre>
     * 订单的编号
     * </pre>
     */
    public java.lang.String getOrderNo() {
      java.lang.Object ref = orderNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          orderNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string orderNo = 1;</code>
     *
     * <pre>
     * 订单的编号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOrderNoBytes() {
      java.lang.Object ref = orderNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYINFO_FIELD_NUMBER = 2;
    private volatile java.lang.Object payInfo_;
    /**
     * <code>optional string payInfo = 2;</code>
     *
     * <pre>
     * 订单的签名信息
     * </pre>
     */
    public java.lang.String getPayInfo() {
      java.lang.Object ref = payInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          payInfo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string payInfo = 2;</code>
     *
     * <pre>
     * 订单的签名信息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPayInfoBytes() {
      java.lang.Object ref = payInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOrderNoBytes().isEmpty()) {
        output.writeBytes(1, getOrderNoBytes());
      }
      if (!getPayInfoBytes().isEmpty()) {
        output.writeBytes(2, getPayInfoBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOrderNoBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getOrderNoBytes());
      }
      if (!getPayInfoBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPayInfoBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.PAlipayOrderInfo}
     *
     * <pre>
     * 生成订单的编号和订单的签名信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.PAlipayOrderInfo)
        com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blemobi.sep.probuf.PaymentProtos.internal_static_common_PAlipayOrderInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blemobi.sep.probuf.PaymentProtos.internal_static_common_PAlipayOrderInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo.class, com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo.Builder.class);
      }

      // Construct using com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        orderNo_ = "";

        payInfo_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blemobi.sep.probuf.PaymentProtos.internal_static_common_PAlipayOrderInfo_descriptor;
      }

      public com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo getDefaultInstanceForType() {
        return com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo.getDefaultInstance();
      }

      public com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo build() {
        com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo buildPartial() {
        com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo result = new com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo(this);
        result.orderNo_ = orderNo_;
        result.payInfo_ = payInfo_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo) {
          return mergeFrom((com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo other) {
        if (other == com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo.getDefaultInstance()) return this;
        if (!other.getOrderNo().isEmpty()) {
          orderNo_ = other.orderNo_;
          onChanged();
        }
        if (!other.getPayInfo().isEmpty()) {
          payInfo_ = other.payInfo_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object orderNo_ = "";
      /**
       * <code>optional string orderNo = 1;</code>
       *
       * <pre>
       * 订单的编号
       * </pre>
       */
      public java.lang.String getOrderNo() {
        java.lang.Object ref = orderNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            orderNo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string orderNo = 1;</code>
       *
       * <pre>
       * 订单的编号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOrderNoBytes() {
        java.lang.Object ref = orderNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string orderNo = 1;</code>
       *
       * <pre>
       * 订单的编号
       * </pre>
       */
      public Builder setOrderNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderNo = 1;</code>
       *
       * <pre>
       * 订单的编号
       * </pre>
       */
      public Builder clearOrderNo() {
        
        orderNo_ = getDefaultInstance().getOrderNo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderNo = 1;</code>
       *
       * <pre>
       * 订单的编号
       * </pre>
       */
      public Builder setOrderNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderNo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object payInfo_ = "";
      /**
       * <code>optional string payInfo = 2;</code>
       *
       * <pre>
       * 订单的签名信息
       * </pre>
       */
      public java.lang.String getPayInfo() {
        java.lang.Object ref = payInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            payInfo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string payInfo = 2;</code>
       *
       * <pre>
       * 订单的签名信息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPayInfoBytes() {
        java.lang.Object ref = payInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          payInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string payInfo = 2;</code>
       *
       * <pre>
       * 订单的签名信息
       * </pre>
       */
      public Builder setPayInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string payInfo = 2;</code>
       *
       * <pre>
       * 订单的签名信息
       * </pre>
       */
      public Builder clearPayInfo() {
        
        payInfo_ = getDefaultInstance().getPayInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string payInfo = 2;</code>
       *
       * <pre>
       * 订单的签名信息
       * </pre>
       */
      public Builder setPayInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payInfo_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:common.PAlipayOrderInfo)
    }

    // @@protoc_insertion_point(class_scope:common.PAlipayOrderInfo)
    private static final com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo();
    }

    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<PAlipayOrderInfo> PARSER =
        new com.google.protobuf.AbstractParser<PAlipayOrderInfo>() {
      public PAlipayOrderInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PAlipayOrderInfo(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PAlipayOrderInfo> getParserForType() {
      return PARSER;
    }

    public com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PAlipayOrderStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.PAlipayOrderStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string orderNo = 1;</code>
     *
     * <pre>
     * 订单的编号
     * </pre>
     */
    java.lang.String getOrderNo();
    /**
     * <code>optional string orderNo = 1;</code>
     *
     * <pre>
     * 订单的编号
     * </pre>
     */
    com.google.protobuf.ByteString
        getOrderNoBytes();

    /**
     * <code>optional string status = 2;</code>
     *
     * <pre>
     * 订单状态， 1--后端收款完成，2--前端已申请支付
     * </pre>
     */
    java.lang.String getStatus();
    /**
     * <code>optional string status = 2;</code>
     *
     * <pre>
     * 订单状态， 1--后端收款完成，2--前端已申请支付
     * </pre>
     */
    com.google.protobuf.ByteString
        getStatusBytes();
  }
  /**
   * Protobuf type {@code common.PAlipayOrderStatus}
   *
   * <pre>
   * 获取支付宝的订单支付状态的返回包
   * </pre>
   */
  public  static final class PAlipayOrderStatus extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:common.PAlipayOrderStatus)
      PAlipayOrderStatusOrBuilder {
    // Use PAlipayOrderStatus.newBuilder() to construct.
    private PAlipayOrderStatus(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private PAlipayOrderStatus() {
      orderNo_ = "";
      status_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PAlipayOrderStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();

              orderNo_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();

              status_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blemobi.sep.probuf.PaymentProtos.internal_static_common_PAlipayOrderStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blemobi.sep.probuf.PaymentProtos.internal_static_common_PAlipayOrderStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus.class, com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus.Builder.class);
    }

    public static final int ORDERNO_FIELD_NUMBER = 1;
    private volatile java.lang.Object orderNo_;
    /**
     * <code>optional string orderNo = 1;</code>
     *
     * <pre>
     * 订单的编号
     * </pre>
     */
    public java.lang.String getOrderNo() {
      java.lang.Object ref = orderNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          orderNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string orderNo = 1;</code>
     *
     * <pre>
     * 订单的编号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOrderNoBytes() {
      java.lang.Object ref = orderNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private volatile java.lang.Object status_;
    /**
     * <code>optional string status = 2;</code>
     *
     * <pre>
     * 订单状态， 1--后端收款完成，2--前端已申请支付
     * </pre>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          status_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string status = 2;</code>
     *
     * <pre>
     * 订单状态， 1--后端收款完成，2--前端已申请支付
     * </pre>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOrderNoBytes().isEmpty()) {
        output.writeBytes(1, getOrderNoBytes());
      }
      if (!getStatusBytes().isEmpty()) {
        output.writeBytes(2, getStatusBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOrderNoBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getOrderNoBytes());
      }
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getStatusBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.PAlipayOrderStatus}
     *
     * <pre>
     * 获取支付宝的订单支付状态的返回包
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.PAlipayOrderStatus)
        com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blemobi.sep.probuf.PaymentProtos.internal_static_common_PAlipayOrderStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blemobi.sep.probuf.PaymentProtos.internal_static_common_PAlipayOrderStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus.class, com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus.Builder.class);
      }

      // Construct using com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        orderNo_ = "";

        status_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blemobi.sep.probuf.PaymentProtos.internal_static_common_PAlipayOrderStatus_descriptor;
      }

      public com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus getDefaultInstanceForType() {
        return com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus.getDefaultInstance();
      }

      public com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus build() {
        com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus buildPartial() {
        com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus result = new com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus(this);
        result.orderNo_ = orderNo_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus) {
          return mergeFrom((com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus other) {
        if (other == com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus.getDefaultInstance()) return this;
        if (!other.getOrderNo().isEmpty()) {
          orderNo_ = other.orderNo_;
          onChanged();
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object orderNo_ = "";
      /**
       * <code>optional string orderNo = 1;</code>
       *
       * <pre>
       * 订单的编号
       * </pre>
       */
      public java.lang.String getOrderNo() {
        java.lang.Object ref = orderNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            orderNo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string orderNo = 1;</code>
       *
       * <pre>
       * 订单的编号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOrderNoBytes() {
        java.lang.Object ref = orderNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string orderNo = 1;</code>
       *
       * <pre>
       * 订单的编号
       * </pre>
       */
      public Builder setOrderNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderNo = 1;</code>
       *
       * <pre>
       * 订单的编号
       * </pre>
       */
      public Builder clearOrderNo() {
        
        orderNo_ = getDefaultInstance().getOrderNo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderNo = 1;</code>
       *
       * <pre>
       * 订单的编号
       * </pre>
       */
      public Builder setOrderNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderNo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>optional string status = 2;</code>
       *
       * <pre>
       * 订单状态， 1--后端收款完成，2--前端已申请支付
       * </pre>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            status_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string status = 2;</code>
       *
       * <pre>
       * 订单状态， 1--后端收款完成，2--前端已申请支付
       * </pre>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string status = 2;</code>
       *
       * <pre>
       * 订单状态， 1--后端收款完成，2--前端已申请支付
       * </pre>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string status = 2;</code>
       *
       * <pre>
       * 订单状态， 1--后端收款完成，2--前端已申请支付
       * </pre>
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>optional string status = 2;</code>
       *
       * <pre>
       * 订单状态， 1--后端收款完成，2--前端已申请支付
       * </pre>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:common.PAlipayOrderStatus)
    }

    // @@protoc_insertion_point(class_scope:common.PAlipayOrderStatus)
    private static final com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus();
    }

    public static com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<PAlipayOrderStatus> PARSER =
        new com.google.protobuf.AbstractParser<PAlipayOrderStatus>() {
      public PAlipayOrderStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PAlipayOrderStatus(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PAlipayOrderStatus> getParserForType() {
      return PARSER;
    }

    public com.blemobi.sep.probuf.PaymentProtos.PAlipayOrderStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_PWeixinPay_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_PWeixinPay_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_PAlipayOrderInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_PAlipayOrderInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_PAlipayOrderStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_PAlipayOrderStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpayment.proto\022\006common\"\225\001\n\nPWeixinPay\022\r" +
      "\n\005appid\030\001 \001(\t\022\021\n\tpartnerid\030\002 \001(\t\022\020\n\010nonc" +
      "estr\030\003 \001(\t\022\021\n\ttimestamp\030\004 \001(\t\022\020\n\010prepayi" +
      "d\030\005 \001(\t\022\017\n\007package\030\006 \001(\t\022\014\n\004sign\030\007 \001(\t\022\017" +
      "\n\007orderNo\030\010 \001(\t\"4\n\020PAlipayOrderInfo\022\017\n\007o" +
      "rderNo\030\001 \001(\t\022\017\n\007payInfo\030\002 \001(\t\"5\n\022PAlipay" +
      "OrderStatus\022\017\n\007orderNo\030\001 \001(\t\022\016\n\006status\030\002" +
      " \001(\tB\'\n\026com.blemobi.sep.probufB\rPaymentP" +
      "rotosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_common_PWeixinPay_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_PWeixinPay_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_PWeixinPay_descriptor,
        new java.lang.String[] { "Appid", "Partnerid", "Noncestr", "Timestamp", "Prepayid", "Package", "Sign", "OrderNo", });
    internal_static_common_PAlipayOrderInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_common_PAlipayOrderInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_PAlipayOrderInfo_descriptor,
        new java.lang.String[] { "OrderNo", "PayInfo", });
    internal_static_common_PAlipayOrderStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_common_PAlipayOrderStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_PAlipayOrderStatus_descriptor,
        new java.lang.String[] { "OrderNo", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
